package main

import (
	"log"

	nats "github.com/nats-io/nats.go"
)

// Order ...
// todo: this struct and the nats code in main() should be generated by AsyncAPI
type Order struct {
	ID     string  `json:"id"`
	Amount float64 `json:"amount"`
}

func main() {
	nc, err := nats.Connect("nats://localhost:4222")
	if err != nil {
		log.Fatal(err)
	}
	// defer nc.Close()
	c, err := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
	if err != nil {
		log.Fatal(err)
	}
	defer c.Close()

	if err := c.Publish("orders", &Order{ID: "123", Amount: 101.01}); err != nil {
		log.Fatal(err)
	}
	// Make sure the message goes through before we close
	c.Flush()

}
