package main

import (
	"log"
	nats "github.com/nats-io/nats.go"
)

// todo: this struct and the nats code in main() should be generated by AsyncAPI
type Order struct {
	ID string `json:"id"`
	Amount float64 `json:"amount"`
}

func main() {
	nc, err := nats.Connect(nats.DefaultURL)
	if err != nil {
		log.Fatal(err)
	}
	// defer nc.Close()
	c, err := nats.NewEncodedConn(nc, nats.JSON_ENCODER)
	if err != nil {
		log.Fatal(err)
	}
defer c.Close()

c.Subscribe("orders", func(o *Order) {
    fmt.Printf("Received an order: %+v\n", o)
})
	
}
